apiVersion: v1
kind: Secret
metadata:
  name: postsecret
type: Opaque
stringData:
  db_username: 'postgres'
  db_password: 'root'
  db_url: 'jdbc:postgresql://10.4.1.21:5432/postDB'
  services_post_clusterip: '10.8.8.10'
  post_port: '9091'
  post_url: 'http://10.8.8.10:9091/'

  