apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-post
spec:
  selector:    
    app: post-service
  type: ClusterIP
  ports:
    - name: post-service
      port: 9091
      targetPort: 9091